server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_test
    username: postgres
    password: password

  jpa:
    database: postgresql
    hibernate.ddl-auto: update
    show-sql: false

  application:
    name: Application-DataJPA

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /user/health-check
        healthCheckInterval: 15s
      config:
        enabled: false